<?xml version="1.0"?>
<package format="2">
  <name>mini_orb_slam</name>
  <version>0.0.1</version>
  <description>Mini ORB-SLAM learning project.</description>

  <maintainer email="user@example.com">mini_orb_user</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>roscpp</depend>
  <depend>roslib</depend>
  <depend>cv_bridge</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>

  <export>
  </export>
</package>
